-- Create tables for UKM Silat Website

-- 1. Pengurus Table
CREATE TABLE public.pengurus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    initials TEXT, -- Displayed in the avatar if no image (though logic generates it, good to have)
    size TEXT DEFAULT 'small', -- 'large', 'medium', 'small' for the bento grid
    order_index INTEGER DEFAULT 0, -- To control display order
    instagram_url TEXT,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Aktivitas Table
CREATE TABLE public.aktivitas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    image_url TEXT, -- Cloudinary URL
    schedule TEXT,
    highlights TEXT[], -- Array of strings
    memories TEXT[], -- Array of strings (simple text list)
    gallery_urls TEXT[], -- Array of Cloudinary URLs
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Events Table
CREATE TABLE public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    date TEXT, -- Keeping as text for flexibility like "Desember 2024" or use DATE type if strict
    location TEXT,
    description TEXT,
    result TEXT, -- e.g., "Juara 1 Kategori Tanding"
    image_url TEXT, -- Cloudinary URL
    status TEXT CHECK (status IN ('upcoming', 'completed')) DEFAULT 'upcoming',
    video_url TEXT,
    instagram_url TEXT,
    gallery_urls TEXT[], -- Array of Cloudinary URLs
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Winners JSONB structure for events (optional, or use a separate table if very complex relation needed)
ALTER TABLE public.events ADD COLUMN winners JSONB; 
-- Structure example: [{"name": "Name", "category": "Kategori", "medal": "gold"}]

-- 4. Prestasi Table (Simpler list for the "Daftar Prestasi" section)
CREATE TABLE public.prestasi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL, -- e.g. "Juara 1 Kategori Tanding"
    event_name TEXT NOT NULL, -- e.g. "Kejurnas ... "
    year TEXT NOT NULL,
    medal TEXT CHECK (medal IN ('gold', 'silver', 'bronze', 'other')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Row Level Security (RLS) Setup
-- Enable RLS
ALTER TABLE public.pengurus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aktivitas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prestasi ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. Public Read (Allows everyone to see data)
CREATE POLICY "Public Read Pengurus" ON public.pengurus FOR SELECT USING (true);
CREATE POLICY "Public Read Aktivitas" ON public.aktivitas FOR SELECT USING (true);
CREATE POLICY "Public Read Events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Public Read Prestasi" ON public.prestasi FOR SELECT USING (true);

-- 2. Admin Write (Allows ONLY specific email to edit)
-- Replace email with your actual admin email
CREATE POLICY "Admin Write Pengurus" ON public.pengurus FOR ALL USING (auth.jwt() ->> 'email' = 'ukmpencaksilatunikom@gmail.com');
CREATE POLICY "Admin Write Aktivitas" ON public.aktivitas FOR ALL USING (auth.jwt() ->> 'email' = 'ukmpencaksilatunikom@gmail.com');
CREATE POLICY "Admin Write Events" ON public.events FOR ALL USING (auth.jwt() ->> 'email' = 'ukmpencaksilatunikom@gmail.com');
CREATE POLICY "Admin Write Prestasi" ON public.prestasi FOR ALL USING (auth.jwt() ->> 'email' = 'ukmpencaksilatunikom@gmail.com');


-- 5. Site Settings Table (Singleton)
CREATE TABLE public.site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT,
    phone TEXT,
    instagram_url TEXT,
    youtube_url TEXT,
    address TEXT,
    training_schedule JSONB DEFAULT '[]'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for site_settings
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
