export { Navbar } from './Navbar'
export { Hero } from './Hero'
export { About } from './About'
export { Achievements } from './Achievements'
export { Prestasi } from './Prestasi'
export { Aktivitas } from './Aktivitas'
export { VisiMisi } from './VisiMisi'
export { Features } from './Features'
export { Team } from './Team'
export { FAQ } from './FAQ'
export { CTA } from './CTA'
export { Footer } from './Footer'
export * from './Icons'

